[package]
name = "my_first_rust_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0" # Or a newer version
queues = "1.0.2"